export default function AiNotice({ children }) {
  return (
    <p className="rounded-md border border-sky-200 bg-sky-50 px-3 py-2 text-sm text-sky-900">
      {children ??
        'This draft was generated by AI from approved sources. It is not published until a dāʿī reviews and approves it.'}
    </p>
  )
}
